version: '3.8'

services:
  mysqldb:
    image: mysql
    container_name: MYSQL
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQLDB_DATABASE
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
    volumes:
      - ./schemas:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysqldb

  frontend:
    build:
      context: ../Client-React
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - backend